import 'package:flutter/material.dart';

/// Translates reference-data crop names returned by the market-price API.
/// Market and district names remain proper nouns, while crop and unit names
/// follow the language selected in BhoomiSetu.
String localizedMarketCropName(BuildContext context, String cropName) {
  final languageCode = Localizations.localeOf(context).languageCode;
  return _cropNames[languageCode]?[cropName] ?? cropName;
}

String localizedMarketPriceUnit(BuildContext context, String unit) {
  if (unit.toLowerCase() != 'quintal') return unit;
  return _perQuintal[Localizations.localeOf(context).languageCode] ??
      'per quintal';
}

const _cropNames = <String, Map<String, String>>{
  'hi': {
    'Wheat': 'गेहूँ',
    'Rice (Basmati)': 'बासमती चावल',
    'Tomato': 'टमाटर',
    'Onion': 'प्याज',
    'Potato': 'आलू',
    'Cotton': 'कपास',
    'Sugarcane': 'गन्ना',
    'Soybean': 'सोयाबीन',
    'Turmeric': 'हल्दी',
    'Mango (Alphonso)': 'अल्फांसो आम',
  },
  'as': {
    'Wheat': 'ঘেঁহু',
    'Rice (Basmati)': 'বাসমতী চাউল',
    'Tomato': 'বিলাহী',
    'Onion': 'পিঁয়াজ',
    'Potato': 'আলু',
    'Cotton': 'কপাহ',
    'Sugarcane': 'কুঁহিয়াৰ',
    'Soybean': 'ছয়াবিন',
    'Turmeric': 'হালধি',
    'Mango (Alphonso)': 'আলফান্সো আম',
  },
  'bn': {
    'Wheat': 'গম',
    'Rice (Basmati)': 'বাসমতি চাল',
    'Tomato': 'টমেটো',
    'Onion': 'পেঁয়াজ',
    'Potato': 'আলু',
    'Cotton': 'তুলা',
    'Sugarcane': 'আখ',
    'Soybean': 'সয়াবিন',
    'Turmeric': 'হলুদ',
    'Mango (Alphonso)': 'আলফানসো আম',
  },
  'gu': {
    'Wheat': 'ઘઉં',
    'Rice (Basmati)': 'બાસમતી ચોખા',
    'Tomato': 'ટામેટા',
    'Onion': 'ડુંગળી',
    'Potato': 'બટાકા',
    'Cotton': 'કપાસ',
    'Sugarcane': 'શેરડી',
    'Soybean': 'સોયાબીન',
    'Turmeric': 'હળદર',
    'Mango (Alphonso)': 'આલ્ફોન્સો કેરી',
  },
  'kn': {
    'Wheat': 'ಗೋಧಿ',
    'Rice (Basmati)': 'ಬಾಸ್ಮತಿ ಅಕ್ಕಿ',
    'Tomato': 'ಟೊಮೇಟೊ',
    'Onion': 'ಈರುಳ್ಳಿ',
    'Potato': 'ಆಲೂಗಡ್ಡೆ',
    'Cotton': 'ಹತ್ತಿ',
    'Sugarcane': 'ಕಬ್ಬು',
    'Soybean': 'ಸೋಯಾಬೀನ್',
    'Turmeric': 'ಅರಿಶಿನ',
    'Mango (Alphonso)': 'ಆಲ್ಫಾನ್ಸೊ ಮಾವು',
  },
  'ml': {
    'Wheat': 'ഗോതമ്പ്',
    'Rice (Basmati)': 'ബസ്മതി അരി',
    'Tomato': 'തക്കാളി',
    'Onion': 'സവാള',
    'Potato': 'ഉരുളക്കിഴങ്ങ്',
    'Cotton': 'പരുത്തി',
    'Sugarcane': 'കരിമ്പ്',
    'Soybean': 'സോയാബീൻ',
    'Turmeric': 'മഞ്ഞൾ',
    'Mango (Alphonso)': 'അൽഫോൻസോ മാമ്പഴം',
  },
  'mr': {
    'Wheat': 'गहू',
    'Rice (Basmati)': 'बासमती तांदूळ',
    'Tomato': 'टोमॅटो',
    'Onion': 'कांदा',
    'Potato': 'बटाटा',
    'Cotton': 'कापूस',
    'Sugarcane': 'ऊस',
    'Soybean': 'सोयाबीन',
    'Turmeric': 'हळद',
    'Mango (Alphonso)': 'हापूस आंबा',
  },
  'or': {
    'Wheat': 'ଗହମ',
    'Rice (Basmati)': 'ବାସମତୀ ଚାଉଳ',
    'Tomato': 'ଟମାଟୋ',
    'Onion': 'ପିଆଜ',
    'Potato': 'ଆଳୁ',
    'Cotton': 'କପା',
    'Sugarcane': 'ଆଖୁ',
    'Soybean': 'ସୋୟାବିନ',
    'Turmeric': 'ହଳଦୀ',
    'Mango (Alphonso)': 'ଆଲଫାନ୍ସୋ ଆମ୍ବ',
  },
  'pa': {
    'Wheat': 'ਕਣਕ',
    'Rice (Basmati)': 'ਬਾਸਮਤੀ ਚੌਲ',
    'Tomato': 'ਟਮਾਟਰ',
    'Onion': 'ਪਿਆਜ਼',
    'Potato': 'ਆਲੂ',
    'Cotton': 'ਕਪਾਹ',
    'Sugarcane': 'ਗੰਨਾ',
    'Soybean': 'ਸੋਇਆਬੀਨ',
    'Turmeric': 'ਹਲਦੀ',
    'Mango (Alphonso)': 'ਅਲਫੋਂਸੋ ਅੰਬ',
  },
  'ta': {
    'Wheat': 'கோதுமை',
    'Rice (Basmati)': 'பாசுமதி அரிசி',
    'Tomato': 'தக்காளி',
    'Onion': 'வெங்காயம்',
    'Potato': 'உருளைக்கிழங்கு',
    'Cotton': 'பருத்தி',
    'Sugarcane': 'கரும்பு',
    'Soybean': 'சோயாபீன்',
    'Turmeric': 'மஞ்சள்',
    'Mango (Alphonso)': 'அல்போன்சா மாம்பழம்',
  },
  'te': {
    'Wheat': 'గోధుమలు',
    'Rice (Basmati)': 'బాస్మతి బియ్యం',
    'Tomato': 'టమాటా',
    'Onion': 'ఉల్లిపాయ',
    'Potato': 'బంగాళాదుంప',
    'Cotton': 'పత్తి',
    'Sugarcane': 'చెరకు',
    'Soybean': 'సోయాబీన్',
    'Turmeric': 'పసుపు',
    'Mango (Alphonso)': 'అల్ఫాన్సో మామిడి',
  },
  'ur': {
    'Wheat': 'گندم',
    'Rice (Basmati)': 'باسمتی چاول',
    'Tomato': 'ٹماٹر',
    'Onion': 'پیاز',
    'Potato': 'آلو',
    'Cotton': 'کپاس',
    'Sugarcane': 'گنا',
    'Soybean': 'سویابین',
    'Turmeric': 'ہلدی',
    'Mango (Alphonso)': 'الفانسو آم',
  },
};

const _perQuintal = <String, String>{
  'hi': 'प्रति क्विंटल',
  'as': 'প্ৰতি কুইণ্টল',
  'bn': 'প্রতি কুইন্টাল',
  'gu': 'પ્રતિ ક્વિન્ટલ',
  'kn': 'ಪ್ರತಿ ಕ್ವಿಂಟಲ್',
  'ml': 'ഒരു ക്വിന്റലിന്',
  'mr': 'प्रति क्विंटल',
  'or': 'ପ୍ରତି କ୍ୱିଣ୍ଟାଲ',
  'pa': 'ਪ੍ਰਤੀ ਕੁਇੰਟਲ',
  'ta': 'குவிண்டாலுக்கு',
  'te': 'క్వింటాల్‌కు',
  'ur': 'فی کوئنٹل',
};
